//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CapaDatos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CuraduriaEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CuraduriaEntities1 usando la cadena de conexión encontrada en la sección 'CuraduriaEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public CuraduriaEntities1() : base("name=CuraduriaEntities1", "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CuraduriaEntities1.
        /// </summary>
        public CuraduriaEntities1(string connectionString) : base(connectionString, "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CuraduriaEntities1.
        /// </summary>
        public CuraduriaEntities1(EntityConnection connection) : base(connection, "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spBuscarTipoDocumento_Result> spBuscarTipoDocumento()
        {
            return base.ExecuteFunction<spBuscarTipoDocumento_Result>("spBuscarTipoDocumento");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="nroSolicitud">No hay documentación de metadatos disponible.</param>
        /// <param name="ruta">No hay documentación de metadatos disponible.</param>
        /// <param name="idTipoDocumento">No hay documentación de metadatos disponible.</param>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spInsertarImagenes_Result> spInsertarImagenes(Nullable<global::System.Int32> nroSolicitud, global::System.String ruta, Nullable<global::System.Int32> idTipoDocumento, global::System.String user)
        {
            ObjectParameter nroSolicitudParameter;
            if (nroSolicitud.HasValue)
            {
                nroSolicitudParameter = new ObjectParameter("nroSolicitud", nroSolicitud);
            }
            else
            {
                nroSolicitudParameter = new ObjectParameter("nroSolicitud", typeof(global::System.Int32));
            }
    
            ObjectParameter rutaParameter;
            if (ruta != null)
            {
                rutaParameter = new ObjectParameter("ruta", ruta);
            }
            else
            {
                rutaParameter = new ObjectParameter("ruta", typeof(global::System.String));
            }
    
            ObjectParameter idTipoDocumentoParameter;
            if (idTipoDocumento.HasValue)
            {
                idTipoDocumentoParameter = new ObjectParameter("idTipoDocumento", idTipoDocumento);
            }
            else
            {
                idTipoDocumentoParameter = new ObjectParameter("idTipoDocumento", typeof(global::System.Int32));
            }
    
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spInsertarImagenes_Result>("spInsertarImagenes", nroSolicitudParameter, rutaParameter, idTipoDocumentoParameter, userParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spGetPerfiles_Result> spGetPerfiles()
        {
            return base.ExecuteFunction<spGetPerfiles_Result>("spGetPerfiles");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="nombre">No hay documentación de metadatos disponible.</param>
        /// <param name="idPerfil">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        /// <param name="nt">No hay documentación de metadatos disponible.</param>
        /// <param name="estado">No hay documentación de metadatos disponible.</param>
        public int spGuardarUsuario(global::System.String user, global::System.String nombre, Nullable<global::System.Int32> idPerfil, global::System.String pass, global::System.String nt, Nullable<global::System.Boolean> estado)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter nombreParameter;
            if (nombre != null)
            {
                nombreParameter = new ObjectParameter("nombre", nombre);
            }
            else
            {
                nombreParameter = new ObjectParameter("nombre", typeof(global::System.String));
            }
    
            ObjectParameter idPerfilParameter;
            if (idPerfil.HasValue)
            {
                idPerfilParameter = new ObjectParameter("idPerfil", idPerfil);
            }
            else
            {
                idPerfilParameter = new ObjectParameter("idPerfil", typeof(global::System.Int32));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            ObjectParameter ntParameter;
            if (nt != null)
            {
                ntParameter = new ObjectParameter("nt", nt);
            }
            else
            {
                ntParameter = new ObjectParameter("nt", typeof(global::System.String));
            }
    
            ObjectParameter estadoParameter;
            if (estado.HasValue)
            {
                estadoParameter = new ObjectParameter("estado", estado);
            }
            else
            {
                estadoParameter = new ObjectParameter("estado", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction("spGuardarUsuario", userParameter, nombreParameter, idPerfilParameter, passParameter, ntParameter, estadoParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="nombre">No hay documentación de metadatos disponible.</param>
        /// <param name="idPerfil">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        /// <param name="nt">No hay documentación de metadatos disponible.</param>
        /// <param name="estado">No hay documentación de metadatos disponible.</param>
        public int spEditarUsuarios(global::System.String user, global::System.String nombre, Nullable<global::System.Int32> idPerfil, global::System.String pass, global::System.String nt, Nullable<global::System.Boolean> estado)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter nombreParameter;
            if (nombre != null)
            {
                nombreParameter = new ObjectParameter("nombre", nombre);
            }
            else
            {
                nombreParameter = new ObjectParameter("nombre", typeof(global::System.String));
            }
    
            ObjectParameter idPerfilParameter;
            if (idPerfil.HasValue)
            {
                idPerfilParameter = new ObjectParameter("idPerfil", idPerfil);
            }
            else
            {
                idPerfilParameter = new ObjectParameter("idPerfil", typeof(global::System.Int32));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            ObjectParameter ntParameter;
            if (nt != null)
            {
                ntParameter = new ObjectParameter("nt", nt);
            }
            else
            {
                ntParameter = new ObjectParameter("nt", typeof(global::System.String));
            }
    
            ObjectParameter estadoParameter;
            if (estado.HasValue)
            {
                estadoParameter = new ObjectParameter("estado", estado);
            }
            else
            {
                estadoParameter = new ObjectParameter("estado", typeof(global::System.Boolean));
            }
    
            return base.ExecuteFunction("spEditarUsuarios", userParameter, nombreParameter, idPerfilParameter, passParameter, ntParameter, estadoParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idSolicitud">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spBuscarSolicitud_Result> spBuscarSolicitud(Nullable<global::System.Int32> idSolicitud)
        {
            ObjectParameter idSolicitudParameter;
            if (idSolicitud.HasValue)
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", idSolicitud);
            }
            else
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spBuscarSolicitud_Result>("spBuscarSolicitud", idSolicitudParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spBuscarUsuarios_Result> spBuscarUsuarios()
        {
            return base.ExecuteFunction<spBuscarUsuarios_Result>("spBuscarUsuarios");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spAutenticacionUsuario_Result> spAutenticacionUsuario(global::System.String user, global::System.String pass)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spAutenticacionUsuario_Result>("spAutenticacionUsuario", userParameter, passParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spGetMenuPerfil_Result> spGetMenuPerfil(global::System.String user)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spGetMenuPerfil_Result>("spGetMenuPerfil", userParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idSolicitud">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spBuscarDocumentosBySolicitud_Result> spBuscarDocumentosBySolicitud(Nullable<global::System.Int32> idSolicitud)
        {
            ObjectParameter idSolicitudParameter;
            if (idSolicitud.HasValue)
            {
                idSolicitudParameter = new ObjectParameter("idSolicitud", idSolicitud);
            }
            else
            {
                idSolicitudParameter = new ObjectParameter("idSolicitud", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spBuscarDocumentosBySolicitud_Result>("spBuscarDocumentosBySolicitud", idSolicitudParameter);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spAutenticacionUsuario_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spAutenticacionUsuario_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spAutenticacionUsuario_Result.
        /// </summary>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        public static spAutenticacionUsuario_Result CreatespAutenticacionUsuario_Result(global::System.String usuario, global::System.String perfil)
        {
            spAutenticacionUsuario_Result spAutenticacionUsuario_Result = new spAutenticacionUsuario_Result();
            spAutenticacionUsuario_Result.Usuario = usuario;
            spAutenticacionUsuario_Result.Perfil = perfil;
            return spAutenticacionUsuario_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarDocumentosBySolicitud_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarDocumentosBySolicitud_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarDocumentosBySolicitud_Result.
        /// </summary>
        /// <param name="idTipoDocumento">Valor inicial de la propiedad IdTipoDocumento.</param>
        /// <param name="documento">Valor inicial de la propiedad Documento.</param>
        /// <param name="idSolicitud">Valor inicial de la propiedad IdSolicitud.</param>
        /// <param name="ruta">Valor inicial de la propiedad Ruta.</param>
        /// <param name="idDocumento">Valor inicial de la propiedad IdDocumento.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad FechaCreacion.</param>
        /// <param name="usuarioCreacion">Valor inicial de la propiedad UsuarioCreacion.</param>
        public static spBuscarDocumentosBySolicitud_Result CreatespBuscarDocumentosBySolicitud_Result(global::System.Int32 idTipoDocumento, global::System.String documento, global::System.Int32 idSolicitud, global::System.String ruta, global::System.Int32 idDocumento, global::System.DateTime fechaCreacion, global::System.String usuarioCreacion)
        {
            spBuscarDocumentosBySolicitud_Result spBuscarDocumentosBySolicitud_Result = new spBuscarDocumentosBySolicitud_Result();
            spBuscarDocumentosBySolicitud_Result.IdTipoDocumento = idTipoDocumento;
            spBuscarDocumentosBySolicitud_Result.Documento = documento;
            spBuscarDocumentosBySolicitud_Result.IdSolicitud = idSolicitud;
            spBuscarDocumentosBySolicitud_Result.Ruta = ruta;
            spBuscarDocumentosBySolicitud_Result.IdDocumento = idDocumento;
            spBuscarDocumentosBySolicitud_Result.FechaCreacion = fechaCreacion;
            spBuscarDocumentosBySolicitud_Result.UsuarioCreacion = usuarioCreacion;
            return spBuscarDocumentosBySolicitud_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoDocumento
        {
            get
            {
                return _IdTipoDocumento;
            }
            set
            {
                OnIdTipoDocumentoChanging(value);
                ReportPropertyChanging("IdTipoDocumento");
                _IdTipoDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoDocumento");
                OnIdTipoDocumentoChanged();
            }
        }
        private global::System.Int32 _IdTipoDocumento;
        partial void OnIdTipoDocumentoChanging(global::System.Int32 value);
        partial void OnIdTipoDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                OnDocumentoChanging(value);
                ReportPropertyChanging("Documento");
                _Documento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Documento");
                OnDocumentoChanged();
            }
        }
        private global::System.String _Documento;
        partial void OnDocumentoChanging(global::System.String value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSolicitud
        {
            get
            {
                return _IdSolicitud;
            }
            set
            {
                OnIdSolicitudChanging(value);
                ReportPropertyChanging("IdSolicitud");
                _IdSolicitud = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSolicitud");
                OnIdSolicitudChanged();
            }
        }
        private global::System.Int32 _IdSolicitud;
        partial void OnIdSolicitudChanging(global::System.Int32 value);
        partial void OnIdSolicitudChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ruta
        {
            get
            {
                return _Ruta;
            }
            set
            {
                OnRutaChanging(value);
                ReportPropertyChanging("Ruta");
                _Ruta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ruta");
                OnRutaChanged();
            }
        }
        private global::System.String _Ruta;
        partial void OnRutaChanging(global::System.String value);
        partial void OnRutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumento
        {
            get
            {
                return _IdDocumento;
            }
            set
            {
                OnIdDocumentoChanging(value);
                ReportPropertyChanging("IdDocumento");
                _IdDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDocumento");
                OnIdDocumentoChanged();
            }
        }
        private global::System.Int32 _IdDocumento;
        partial void OnIdDocumentoChanging(global::System.Int32 value);
        partial void OnIdDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioCreacion
        {
            get
            {
                return _UsuarioCreacion;
            }
            set
            {
                OnUsuarioCreacionChanging(value);
                ReportPropertyChanging("UsuarioCreacion");
                _UsuarioCreacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioCreacion");
                OnUsuarioCreacionChanged();
            }
        }
        private global::System.String _UsuarioCreacion;
        partial void OnUsuarioCreacionChanging(global::System.String value);
        partial void OnUsuarioCreacionChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarSolicitud_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarSolicitud_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RESULTADO
        {
            get
            {
                return _RESULTADO;
            }
            set
            {
                OnRESULTADOChanging(value);
                ReportPropertyChanging("RESULTADO");
                _RESULTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RESULTADO");
                OnRESULTADOChanged();
            }
        }
        private Nullable<global::System.Int32> _RESULTADO;
        partial void OnRESULTADOChanging(Nullable<global::System.Int32> value);
        partial void OnRESULTADOChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarTipoDocumento_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarTipoDocumento_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarTipoDocumento_Result.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="documento">Valor inicial de la propiedad documento.</param>
        public static spBuscarTipoDocumento_Result CreatespBuscarTipoDocumento_Result(global::System.Int32 id, global::System.String documento)
        {
            spBuscarTipoDocumento_Result spBuscarTipoDocumento_Result = new spBuscarTipoDocumento_Result();
            spBuscarTipoDocumento_Result.id = id;
            spBuscarTipoDocumento_Result.documento = documento;
            return spBuscarTipoDocumento_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documento
        {
            get
            {
                return _documento;
            }
            set
            {
                OndocumentoChanging(value);
                ReportPropertyChanging("documento");
                _documento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documento");
                OndocumentoChanged();
            }
        }
        private global::System.String _documento;
        partial void OndocumentoChanging(global::System.String value);
        partial void OndocumentoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarUsuarios_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarUsuarios_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarUsuarios_Result.
        /// </summary>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="nombre_Completo">Valor inicial de la propiedad Nombre_Completo.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        /// <param name="fecha_Creacion">Valor inicial de la propiedad Fecha_Creacion.</param>
        /// <param name="idPerfil">Valor inicial de la propiedad IdPerfil.</param>
        public static spBuscarUsuarios_Result CreatespBuscarUsuarios_Result(global::System.String usuario, global::System.String nombre_Completo, global::System.String perfil, global::System.DateTime fecha_Creacion, global::System.Int32 idPerfil)
        {
            spBuscarUsuarios_Result spBuscarUsuarios_Result = new spBuscarUsuarios_Result();
            spBuscarUsuarios_Result.Usuario = usuario;
            spBuscarUsuarios_Result.Nombre_Completo = nombre_Completo;
            spBuscarUsuarios_Result.Perfil = perfil;
            spBuscarUsuarios_Result.Fecha_Creacion = fecha_Creacion;
            spBuscarUsuarios_Result.IdPerfil = idPerfil;
            return spBuscarUsuarios_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Completo
        {
            get
            {
                return _Nombre_Completo;
            }
            set
            {
                OnNombre_CompletoChanging(value);
                ReportPropertyChanging("Nombre_Completo");
                _Nombre_Completo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre_Completo");
                OnNombre_CompletoChanged();
            }
        }
        private global::System.String _Nombre_Completo;
        partial void OnNombre_CompletoChanging(global::System.String value);
        partial void OnNombre_CompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha_Creacion
        {
            get
            {
                return _Fecha_Creacion;
            }
            set
            {
                OnFecha_CreacionChanging(value);
                ReportPropertyChanging("Fecha_Creacion");
                _Fecha_Creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Creacion");
                OnFecha_CreacionChanged();
            }
        }
        private global::System.DateTime _Fecha_Creacion;
        partial void OnFecha_CreacionChanging(global::System.DateTime value);
        partial void OnFecha_CreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                OnIdPerfilChanging(value);
                ReportPropertyChanging("IdPerfil");
                _IdPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPerfil");
                OnIdPerfilChanged();
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetMenuPerfil_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetMenuPerfil_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetMenuPerfil_Result.
        /// </summary>
        /// <param name="menu">Valor inicial de la propiedad Menu.</param>
        /// <param name="nombreFormulario">Valor inicial de la propiedad NombreFormulario.</param>
        public static spGetMenuPerfil_Result CreatespGetMenuPerfil_Result(global::System.String menu, global::System.String nombreFormulario)
        {
            spGetMenuPerfil_Result spGetMenuPerfil_Result = new spGetMenuPerfil_Result();
            spGetMenuPerfil_Result.Menu = menu;
            spGetMenuPerfil_Result.NombreFormulario = nombreFormulario;
            return spGetMenuPerfil_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Menu
        {
            get
            {
                return _Menu;
            }
            set
            {
                OnMenuChanging(value);
                ReportPropertyChanging("Menu");
                _Menu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Menu");
                OnMenuChanged();
            }
        }
        private global::System.String _Menu;
        partial void OnMenuChanging(global::System.String value);
        partial void OnMenuChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreFormulario
        {
            get
            {
                return _NombreFormulario;
            }
            set
            {
                OnNombreFormularioChanging(value);
                ReportPropertyChanging("NombreFormulario");
                _NombreFormulario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreFormulario");
                OnNombreFormularioChanged();
            }
        }
        private global::System.String _NombreFormulario;
        partial void OnNombreFormularioChanging(global::System.String value);
        partial void OnNombreFormularioChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetPerfiles_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetPerfiles_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetPerfiles_Result.
        /// </summary>
        /// <param name="idPerfil">Valor inicial de la propiedad IdPerfil.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        public static spGetPerfiles_Result CreatespGetPerfiles_Result(global::System.Int32 idPerfil, global::System.String perfil)
        {
            spGetPerfiles_Result spGetPerfiles_Result = new spGetPerfiles_Result();
            spGetPerfiles_Result.IdPerfil = idPerfil;
            spGetPerfiles_Result.Perfil = perfil;
            return spGetPerfiles_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                OnIdPerfilChanging(value);
                ReportPropertyChanging("IdPerfil");
                _IdPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPerfil");
                OnIdPerfilChanged();
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spInsertarImagenes_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spInsertarImagenes_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resultado
        {
            get
            {
                return _resultado;
            }
            set
            {
                OnresultadoChanging(value);
                ReportPropertyChanging("resultado");
                _resultado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resultado");
                OnresultadoChanged();
            }
        }
        private global::System.String _resultado;
        partial void OnresultadoChanging(global::System.String value);
        partial void OnresultadoChanged();

        #endregion

    }

    #endregion

    
}
