//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CapaDatos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CuraduriaEntities1 : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CuraduriaEntities1 usando la cadena de conexión encontrada en la sección 'CuraduriaEntities1' del archivo de configuración de la aplicación.
        /// </summary>
        public CuraduriaEntities1() : base("name=CuraduriaEntities1", "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CuraduriaEntities1.
        /// </summary>
        public CuraduriaEntities1(string connectionString) : base(connectionString, "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CuraduriaEntities1.
        /// </summary>
        public CuraduriaEntities1(EntityConnection connection) : base(connection, "CuraduriaEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Importaciones de funciones
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spBuscarTipoDocumento_Result> spBuscarTipoDocumento()
        {
            return base.ExecuteFunction<spBuscarTipoDocumento_Result>("spBuscarTipoDocumento");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="nroSolicitud">No hay documentación de metadatos disponible.</param>
        /// <param name="ruta">No hay documentación de metadatos disponible.</param>
        /// <param name="idTipoDocumento">No hay documentación de metadatos disponible.</param>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spInsertarImagenes_Result> spInsertarImagenes(Nullable<global::System.Int32> nroSolicitud, global::System.String ruta, Nullable<global::System.Int32> idTipoDocumento, global::System.String user)
        {
            ObjectParameter nroSolicitudParameter;
            if (nroSolicitud.HasValue)
            {
                nroSolicitudParameter = new ObjectParameter("nroSolicitud", nroSolicitud);
            }
            else
            {
                nroSolicitudParameter = new ObjectParameter("nroSolicitud", typeof(global::System.Int32));
            }
    
            ObjectParameter rutaParameter;
            if (ruta != null)
            {
                rutaParameter = new ObjectParameter("ruta", ruta);
            }
            else
            {
                rutaParameter = new ObjectParameter("ruta", typeof(global::System.String));
            }
    
            ObjectParameter idTipoDocumentoParameter;
            if (idTipoDocumento.HasValue)
            {
                idTipoDocumentoParameter = new ObjectParameter("idTipoDocumento", idTipoDocumento);
            }
            else
            {
                idTipoDocumentoParameter = new ObjectParameter("idTipoDocumento", typeof(global::System.Int32));
            }
    
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spInsertarImagenes_Result>("spInsertarImagenes", nroSolicitudParameter, rutaParameter, idTipoDocumentoParameter, userParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spGetPerfiles_Result> spGetPerfiles()
        {
            return base.ExecuteFunction<spGetPerfiles_Result>("spGetPerfiles");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idSolicitud">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spBuscarSolicitud_Result> spBuscarSolicitud(Nullable<global::System.Int32> idSolicitud)
        {
            ObjectParameter idSolicitudParameter;
            if (idSolicitud.HasValue)
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", idSolicitud);
            }
            else
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spBuscarSolicitud_Result>("spBuscarSolicitud", idSolicitudParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spAutenticacionUsuario_Result> spAutenticacionUsuario(global::System.String user, global::System.String pass)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spAutenticacionUsuario_Result>("spAutenticacionUsuario", userParameter, passParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spGetMenuPerfil_Result> spGetMenuPerfil(global::System.String user)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spGetMenuPerfil_Result>("spGetMenuPerfil", userParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idSolicitud">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spBuscarDocumentosBySolicitud_Result> spBuscarDocumentosBySolicitud(Nullable<global::System.Int32> idSolicitud)
        {
            ObjectParameter idSolicitudParameter;
            if (idSolicitud.HasValue)
            {
                idSolicitudParameter = new ObjectParameter("idSolicitud", idSolicitud);
            }
            else
            {
                idSolicitudParameter = new ObjectParameter("idSolicitud", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spBuscarDocumentosBySolicitud_Result>("spBuscarDocumentosBySolicitud", idSolicitudParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spGetTipoTramite_Result> spGetTipoTramite()
        {
            return base.ExecuteFunction<spGetTipoTramite_Result>("spGetTipoTramite");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="sUsuario">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spGetUsuarioTipoTramite_Result> spGetUsuarioTipoTramite(global::System.String sUsuario)
        {
            ObjectParameter sUsuarioParameter;
            if (sUsuario != null)
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", sUsuario);
            }
            else
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spGetUsuarioTipoTramite_Result>("spGetUsuarioTipoTramite", sUsuarioParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="sUsuario">No hay documentación de metadatos disponible.</param>
        /// <param name="nIdTipoTramite">No hay documentación de metadatos disponible.</param>
        /// <param name="nAction">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spInsDelValUsuarioTipoTramite_Result> spInsDelValUsuarioTipoTramite(global::System.String sUsuario, Nullable<global::System.Int32> nIdTipoTramite, Nullable<global::System.Int32> nAction)
        {
            ObjectParameter sUsuarioParameter;
            if (sUsuario != null)
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", sUsuario);
            }
            else
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", typeof(global::System.String));
            }
    
            ObjectParameter nIdTipoTramiteParameter;
            if (nIdTipoTramite.HasValue)
            {
                nIdTipoTramiteParameter = new ObjectParameter("nIdTipoTramite", nIdTipoTramite);
            }
            else
            {
                nIdTipoTramiteParameter = new ObjectParameter("nIdTipoTramite", typeof(global::System.Int32));
            }
    
            ObjectParameter nActionParameter;
            if (nAction.HasValue)
            {
                nActionParameter = new ObjectParameter("nAction", nAction);
            }
            else
            {
                nActionParameter = new ObjectParameter("nAction", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spInsDelValUsuarioTipoTramite_Result>("spInsDelValUsuarioTipoTramite", sUsuarioParameter, nIdTipoTramiteParameter, nActionParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="nombre">No hay documentación de metadatos disponible.</param>
        /// <param name="idPerfil">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        /// <param name="nt">No hay documentación de metadatos disponible.</param>
        /// <param name="estado">No hay documentación de metadatos disponible.</param>
        /// <param name="correo">No hay documentación de metadatos disponible.</param>
        public int spGuardarUsuario(global::System.String user, global::System.String nombre, Nullable<global::System.Int32> idPerfil, global::System.String pass, global::System.String nt, Nullable<global::System.Boolean> estado, global::System.String correo)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter nombreParameter;
            if (nombre != null)
            {
                nombreParameter = new ObjectParameter("nombre", nombre);
            }
            else
            {
                nombreParameter = new ObjectParameter("nombre", typeof(global::System.String));
            }
    
            ObjectParameter idPerfilParameter;
            if (idPerfil.HasValue)
            {
                idPerfilParameter = new ObjectParameter("idPerfil", idPerfil);
            }
            else
            {
                idPerfilParameter = new ObjectParameter("idPerfil", typeof(global::System.Int32));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            ObjectParameter ntParameter;
            if (nt != null)
            {
                ntParameter = new ObjectParameter("nt", nt);
            }
            else
            {
                ntParameter = new ObjectParameter("nt", typeof(global::System.String));
            }
    
            ObjectParameter estadoParameter;
            if (estado.HasValue)
            {
                estadoParameter = new ObjectParameter("estado", estado);
            }
            else
            {
                estadoParameter = new ObjectParameter("estado", typeof(global::System.Boolean));
            }
    
            ObjectParameter correoParameter;
            if (correo != null)
            {
                correoParameter = new ObjectParameter("correo", correo);
            }
            else
            {
                correoParameter = new ObjectParameter("correo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spGuardarUsuario", userParameter, nombreParameter, idPerfilParameter, passParameter, ntParameter, estadoParameter, correoParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="user">No hay documentación de metadatos disponible.</param>
        /// <param name="nombre">No hay documentación de metadatos disponible.</param>
        /// <param name="idPerfil">No hay documentación de metadatos disponible.</param>
        /// <param name="pass">No hay documentación de metadatos disponible.</param>
        /// <param name="nt">No hay documentación de metadatos disponible.</param>
        /// <param name="estado">No hay documentación de metadatos disponible.</param>
        /// <param name="correo">No hay documentación de metadatos disponible.</param>
        public int spEditarUsuarios(global::System.String user, global::System.String nombre, Nullable<global::System.Int32> idPerfil, global::System.String pass, global::System.String nt, Nullable<global::System.Boolean> estado, global::System.String correo)
        {
            ObjectParameter userParameter;
            if (user != null)
            {
                userParameter = new ObjectParameter("user", user);
            }
            else
            {
                userParameter = new ObjectParameter("user", typeof(global::System.String));
            }
    
            ObjectParameter nombreParameter;
            if (nombre != null)
            {
                nombreParameter = new ObjectParameter("nombre", nombre);
            }
            else
            {
                nombreParameter = new ObjectParameter("nombre", typeof(global::System.String));
            }
    
            ObjectParameter idPerfilParameter;
            if (idPerfil.HasValue)
            {
                idPerfilParameter = new ObjectParameter("idPerfil", idPerfil);
            }
            else
            {
                idPerfilParameter = new ObjectParameter("idPerfil", typeof(global::System.Int32));
            }
    
            ObjectParameter passParameter;
            if (pass != null)
            {
                passParameter = new ObjectParameter("pass", pass);
            }
            else
            {
                passParameter = new ObjectParameter("pass", typeof(global::System.String));
            }
    
            ObjectParameter ntParameter;
            if (nt != null)
            {
                ntParameter = new ObjectParameter("nt", nt);
            }
            else
            {
                ntParameter = new ObjectParameter("nt", typeof(global::System.String));
            }
    
            ObjectParameter estadoParameter;
            if (estado.HasValue)
            {
                estadoParameter = new ObjectParameter("estado", estado);
            }
            else
            {
                estadoParameter = new ObjectParameter("estado", typeof(global::System.Boolean));
            }
    
            ObjectParameter correoParameter;
            if (correo != null)
            {
                correoParameter = new ObjectParameter("correo", correo);
            }
            else
            {
                correoParameter = new ObjectParameter("correo", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spEditarUsuarios", userParameter, nombreParameter, idPerfilParameter, passParameter, ntParameter, estadoParameter, correoParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="sUsuario">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spBuscarUsuarios_Result> spBuscarUsuarios(global::System.String sUsuario)
        {
            ObjectParameter sUsuarioParameter;
            if (sUsuario != null)
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", sUsuario);
            }
            else
            {
                sUsuarioParameter = new ObjectParameter("sUsuario", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spBuscarUsuarios_Result>("spBuscarUsuarios", sUsuarioParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idSolicitud">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spGetTipoTramiteBySolicitud_Result> spGetTipoTramiteBySolicitud(Nullable<global::System.Int32> idSolicitud)
        {
            ObjectParameter idSolicitudParameter;
            if (idSolicitud.HasValue)
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", idSolicitud);
            }
            else
            {
                idSolicitudParameter = new ObjectParameter("IdSolicitud", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spGetTipoTramiteBySolicitud_Result>("spGetTipoTramiteBySolicitud", idSolicitudParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="idTipoTramite">No hay documentación de metadatos disponible.</param>
        public ObjectResult<spGetCorreosNotificacion_Result> spGetCorreosNotificacion(Nullable<global::System.Int32> idTipoTramite)
        {
            ObjectParameter idTipoTramiteParameter;
            if (idTipoTramite.HasValue)
            {
                idTipoTramiteParameter = new ObjectParameter("IdTipoTramite", idTipoTramite);
            }
            else
            {
                idTipoTramiteParameter = new ObjectParameter("IdTipoTramite", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spGetCorreosNotificacion_Result>("spGetCorreosNotificacion", idTipoTramiteParameter);
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectResult<spGetOpcSistema_Result> spGetOpcSistema()
        {
            return base.ExecuteFunction<spGetOpcSistema_Result>("spGetOpcSistema");
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        /// <param name="nNotificacionMail">No hay documentación de metadatos disponible.</param>
        public int spUpdOpcSistema(Nullable<global::System.Int32> nNotificacionMail)
        {
            ObjectParameter nNotificacionMailParameter;
            if (nNotificacionMail.HasValue)
            {
                nNotificacionMailParameter = new ObjectParameter("nNotificacionMail", nNotificacionMail);
            }
            else
            {
                nNotificacionMailParameter = new ObjectParameter("nNotificacionMail", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction("spUpdOpcSistema", nNotificacionMailParameter);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spAutenticacionUsuario_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spAutenticacionUsuario_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spAutenticacionUsuario_Result.
        /// </summary>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        public static spAutenticacionUsuario_Result CreatespAutenticacionUsuario_Result(global::System.String usuario, global::System.String perfil)
        {
            spAutenticacionUsuario_Result spAutenticacionUsuario_Result = new spAutenticacionUsuario_Result();
            spAutenticacionUsuario_Result.Usuario = usuario;
            spAutenticacionUsuario_Result.Perfil = perfil;
            return spAutenticacionUsuario_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarDocumentosBySolicitud_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarDocumentosBySolicitud_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarDocumentosBySolicitud_Result.
        /// </summary>
        /// <param name="idTipoDocumento">Valor inicial de la propiedad IdTipoDocumento.</param>
        /// <param name="documento">Valor inicial de la propiedad Documento.</param>
        /// <param name="idSolicitud">Valor inicial de la propiedad IdSolicitud.</param>
        /// <param name="ruta">Valor inicial de la propiedad Ruta.</param>
        /// <param name="idDocumento">Valor inicial de la propiedad IdDocumento.</param>
        /// <param name="fechaCreacion">Valor inicial de la propiedad FechaCreacion.</param>
        /// <param name="usuarioCreacion">Valor inicial de la propiedad UsuarioCreacion.</param>
        public static spBuscarDocumentosBySolicitud_Result CreatespBuscarDocumentosBySolicitud_Result(global::System.Int32 idTipoDocumento, global::System.String documento, global::System.Int32 idSolicitud, global::System.String ruta, global::System.Int32 idDocumento, global::System.DateTime fechaCreacion, global::System.String usuarioCreacion)
        {
            spBuscarDocumentosBySolicitud_Result spBuscarDocumentosBySolicitud_Result = new spBuscarDocumentosBySolicitud_Result();
            spBuscarDocumentosBySolicitud_Result.IdTipoDocumento = idTipoDocumento;
            spBuscarDocumentosBySolicitud_Result.Documento = documento;
            spBuscarDocumentosBySolicitud_Result.IdSolicitud = idSolicitud;
            spBuscarDocumentosBySolicitud_Result.Ruta = ruta;
            spBuscarDocumentosBySolicitud_Result.IdDocumento = idDocumento;
            spBuscarDocumentosBySolicitud_Result.FechaCreacion = fechaCreacion;
            spBuscarDocumentosBySolicitud_Result.UsuarioCreacion = usuarioCreacion;
            return spBuscarDocumentosBySolicitud_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoDocumento
        {
            get
            {
                return _IdTipoDocumento;
            }
            set
            {
                OnIdTipoDocumentoChanging(value);
                ReportPropertyChanging("IdTipoDocumento");
                _IdTipoDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoDocumento");
                OnIdTipoDocumentoChanged();
            }
        }
        private global::System.Int32 _IdTipoDocumento;
        partial void OnIdTipoDocumentoChanging(global::System.Int32 value);
        partial void OnIdTipoDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Documento
        {
            get
            {
                return _Documento;
            }
            set
            {
                OnDocumentoChanging(value);
                ReportPropertyChanging("Documento");
                _Documento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Documento");
                OnDocumentoChanged();
            }
        }
        private global::System.String _Documento;
        partial void OnDocumentoChanging(global::System.String value);
        partial void OnDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdSolicitud
        {
            get
            {
                return _IdSolicitud;
            }
            set
            {
                OnIdSolicitudChanging(value);
                ReportPropertyChanging("IdSolicitud");
                _IdSolicitud = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdSolicitud");
                OnIdSolicitudChanged();
            }
        }
        private global::System.Int32 _IdSolicitud;
        partial void OnIdSolicitudChanging(global::System.Int32 value);
        partial void OnIdSolicitudChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ruta
        {
            get
            {
                return _Ruta;
            }
            set
            {
                OnRutaChanging(value);
                ReportPropertyChanging("Ruta");
                _Ruta = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Ruta");
                OnRutaChanged();
            }
        }
        private global::System.String _Ruta;
        partial void OnRutaChanging(global::System.String value);
        partial void OnRutaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdDocumento
        {
            get
            {
                return _IdDocumento;
            }
            set
            {
                OnIdDocumentoChanging(value);
                ReportPropertyChanging("IdDocumento");
                _IdDocumento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdDocumento");
                OnIdDocumentoChanged();
            }
        }
        private global::System.Int32 _IdDocumento;
        partial void OnIdDocumentoChanging(global::System.Int32 value);
        partial void OnIdDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                OnFechaCreacionChanging(value);
                ReportPropertyChanging("FechaCreacion");
                _FechaCreacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaCreacion");
                OnFechaCreacionChanged();
            }
        }
        private global::System.DateTime _FechaCreacion;
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        partial void OnFechaCreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UsuarioCreacion
        {
            get
            {
                return _UsuarioCreacion;
            }
            set
            {
                OnUsuarioCreacionChanging(value);
                ReportPropertyChanging("UsuarioCreacion");
                _UsuarioCreacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UsuarioCreacion");
                OnUsuarioCreacionChanged();
            }
        }
        private global::System.String _UsuarioCreacion;
        partial void OnUsuarioCreacionChanging(global::System.String value);
        partial void OnUsuarioCreacionChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarSolicitud_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarSolicitud_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RESULTADO
        {
            get
            {
                return _RESULTADO;
            }
            set
            {
                OnRESULTADOChanging(value);
                ReportPropertyChanging("RESULTADO");
                _RESULTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RESULTADO");
                OnRESULTADOChanged();
            }
        }
        private Nullable<global::System.Int32> _RESULTADO;
        partial void OnRESULTADOChanging(Nullable<global::System.Int32> value);
        partial void OnRESULTADOChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarTipoDocumento_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarTipoDocumento_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarTipoDocumento_Result.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="documento">Valor inicial de la propiedad documento.</param>
        public static spBuscarTipoDocumento_Result CreatespBuscarTipoDocumento_Result(global::System.Int32 id, global::System.String documento)
        {
            spBuscarTipoDocumento_Result spBuscarTipoDocumento_Result = new spBuscarTipoDocumento_Result();
            spBuscarTipoDocumento_Result.id = id;
            spBuscarTipoDocumento_Result.documento = documento;
            return spBuscarTipoDocumento_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                OnidChanging(value);
                ReportPropertyChanging("id");
                _id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id");
                OnidChanged();
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String documento
        {
            get
            {
                return _documento;
            }
            set
            {
                OndocumentoChanging(value);
                ReportPropertyChanging("documento");
                _documento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("documento");
                OndocumentoChanged();
            }
        }
        private global::System.String _documento;
        partial void OndocumentoChanging(global::System.String value);
        partial void OndocumentoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spBuscarUsuarios_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spBuscarUsuarios_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spBuscarUsuarios_Result.
        /// </summary>
        /// <param name="usuario">Valor inicial de la propiedad Usuario.</param>
        /// <param name="nombre_Completo">Valor inicial de la propiedad Nombre_Completo.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        /// <param name="fecha_Creacion">Valor inicial de la propiedad Fecha_Creacion.</param>
        /// <param name="idPerfil">Valor inicial de la propiedad IdPerfil.</param>
        public static spBuscarUsuarios_Result CreatespBuscarUsuarios_Result(global::System.String usuario, global::System.String nombre_Completo, global::System.String perfil, global::System.DateTime fecha_Creacion, global::System.Int32 idPerfil)
        {
            spBuscarUsuarios_Result spBuscarUsuarios_Result = new spBuscarUsuarios_Result();
            spBuscarUsuarios_Result.Usuario = usuario;
            spBuscarUsuarios_Result.Nombre_Completo = nombre_Completo;
            spBuscarUsuarios_Result.Perfil = perfil;
            spBuscarUsuarios_Result.Fecha_Creacion = fecha_Creacion;
            spBuscarUsuarios_Result.IdPerfil = idPerfil;
            return spBuscarUsuarios_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Usuario
        {
            get
            {
                return _Usuario;
            }
            set
            {
                OnUsuarioChanging(value);
                ReportPropertyChanging("Usuario");
                _Usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Usuario");
                OnUsuarioChanged();
            }
        }
        private global::System.String _Usuario;
        partial void OnUsuarioChanging(global::System.String value);
        partial void OnUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre_Completo
        {
            get
            {
                return _Nombre_Completo;
            }
            set
            {
                OnNombre_CompletoChanging(value);
                ReportPropertyChanging("Nombre_Completo");
                _Nombre_Completo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre_Completo");
                OnNombre_CompletoChanged();
            }
        }
        private global::System.String _Nombre_Completo;
        partial void OnNombre_CompletoChanging(global::System.String value);
        partial void OnNombre_CompletoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha_Creacion
        {
            get
            {
                return _Fecha_Creacion;
            }
            set
            {
                OnFecha_CreacionChanging(value);
                ReportPropertyChanging("Fecha_Creacion");
                _Fecha_Creacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha_Creacion");
                OnFecha_CreacionChanged();
            }
        }
        private global::System.DateTime _Fecha_Creacion;
        partial void OnFecha_CreacionChanging(global::System.DateTime value);
        partial void OnFecha_CreacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                OnIdPerfilChanging(value);
                ReportPropertyChanging("IdPerfil");
                _IdPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPerfil");
                OnIdPerfilChanged();
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetCorreosNotificacion_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetCorreosNotificacion_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetMenuPerfil_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetMenuPerfil_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetMenuPerfil_Result.
        /// </summary>
        /// <param name="menu">Valor inicial de la propiedad Menu.</param>
        /// <param name="nombreFormulario">Valor inicial de la propiedad NombreFormulario.</param>
        public static spGetMenuPerfil_Result CreatespGetMenuPerfil_Result(global::System.String menu, global::System.String nombreFormulario)
        {
            spGetMenuPerfil_Result spGetMenuPerfil_Result = new spGetMenuPerfil_Result();
            spGetMenuPerfil_Result.Menu = menu;
            spGetMenuPerfil_Result.NombreFormulario = nombreFormulario;
            return spGetMenuPerfil_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Menu
        {
            get
            {
                return _Menu;
            }
            set
            {
                OnMenuChanging(value);
                ReportPropertyChanging("Menu");
                _Menu = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Menu");
                OnMenuChanged();
            }
        }
        private global::System.String _Menu;
        partial void OnMenuChanging(global::System.String value);
        partial void OnMenuChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreFormulario
        {
            get
            {
                return _NombreFormulario;
            }
            set
            {
                OnNombreFormularioChanging(value);
                ReportPropertyChanging("NombreFormulario");
                _NombreFormulario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreFormulario");
                OnNombreFormularioChanged();
            }
        }
        private global::System.String _NombreFormulario;
        partial void OnNombreFormularioChanging(global::System.String value);
        partial void OnNombreFormularioChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetOpcSistema_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetOpcSistema_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetOpcSistema_Result.
        /// </summary>
        /// <param name="nId">Valor inicial de la propiedad nId.</param>
        public static spGetOpcSistema_Result CreatespGetOpcSistema_Result(global::System.Int32 nId)
        {
            spGetOpcSistema_Result spGetOpcSistema_Result = new spGetOpcSistema_Result();
            spGetOpcSistema_Result.nId = nId;
            return spGetOpcSistema_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nId
        {
            get
            {
                return _nId;
            }
            set
            {
                OnnIdChanging(value);
                ReportPropertyChanging("nId");
                _nId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nId");
                OnnIdChanged();
            }
        }
        private global::System.Int32 _nId;
        partial void OnnIdChanging(global::System.Int32 value);
        partial void OnnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nNotificacionMail
        {
            get
            {
                return _nNotificacionMail;
            }
            set
            {
                OnnNotificacionMailChanging(value);
                ReportPropertyChanging("nNotificacionMail");
                _nNotificacionMail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nNotificacionMail");
                OnnNotificacionMailChanged();
            }
        }
        private Nullable<global::System.Int32> _nNotificacionMail;
        partial void OnnNotificacionMailChanging(Nullable<global::System.Int32> value);
        partial void OnnNotificacionMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sFromMail
        {
            get
            {
                return _sFromMail;
            }
            set
            {
                OnsFromMailChanging(value);
                ReportPropertyChanging("sFromMail");
                _sFromMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sFromMail");
                OnsFromMailChanged();
            }
        }
        private global::System.String _sFromMail;
        partial void OnsFromMailChanging(global::System.String value);
        partial void OnsFromMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sSubjectMail
        {
            get
            {
                return _sSubjectMail;
            }
            set
            {
                OnsSubjectMailChanging(value);
                ReportPropertyChanging("sSubjectMail");
                _sSubjectMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sSubjectMail");
                OnsSubjectMailChanged();
            }
        }
        private global::System.String _sSubjectMail;
        partial void OnsSubjectMailChanging(global::System.String value);
        partial void OnsSubjectMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sBodyMail
        {
            get
            {
                return _sBodyMail;
            }
            set
            {
                OnsBodyMailChanging(value);
                ReportPropertyChanging("sBodyMail");
                _sBodyMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sBodyMail");
                OnsBodyMailChanged();
            }
        }
        private global::System.String _sBodyMail;
        partial void OnsBodyMailChanging(global::System.String value);
        partial void OnsBodyMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sUserNameCredentialsMail
        {
            get
            {
                return _sUserNameCredentialsMail;
            }
            set
            {
                OnsUserNameCredentialsMailChanging(value);
                ReportPropertyChanging("sUserNameCredentialsMail");
                _sUserNameCredentialsMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sUserNameCredentialsMail");
                OnsUserNameCredentialsMailChanged();
            }
        }
        private global::System.String _sUserNameCredentialsMail;
        partial void OnsUserNameCredentialsMailChanging(global::System.String value);
        partial void OnsUserNameCredentialsMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sPasswordCredentialsMail
        {
            get
            {
                return _sPasswordCredentialsMail;
            }
            set
            {
                OnsPasswordCredentialsMailChanging(value);
                ReportPropertyChanging("sPasswordCredentialsMail");
                _sPasswordCredentialsMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sPasswordCredentialsMail");
                OnsPasswordCredentialsMailChanged();
            }
        }
        private global::System.String _sPasswordCredentialsMail;
        partial void OnsPasswordCredentialsMailChanging(global::System.String value);
        partial void OnsPasswordCredentialsMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sHostMail
        {
            get
            {
                return _sHostMail;
            }
            set
            {
                OnsHostMailChanging(value);
                ReportPropertyChanging("sHostMail");
                _sHostMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sHostMail");
                OnsHostMailChanged();
            }
        }
        private global::System.String _sHostMail;
        partial void OnsHostMailChanging(global::System.String value);
        partial void OnsHostMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nPortMail
        {
            get
            {
                return _nPortMail;
            }
            set
            {
                OnnPortMailChanging(value);
                ReportPropertyChanging("nPortMail");
                _nPortMail = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nPortMail");
                OnnPortMailChanged();
            }
        }
        private Nullable<global::System.Int32> _nPortMail;
        partial void OnnPortMailChanging(Nullable<global::System.Int32> value);
        partial void OnnPortMailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> bEnableSsl
        {
            get
            {
                return _bEnableSsl;
            }
            set
            {
                OnbEnableSslChanging(value);
                ReportPropertyChanging("bEnableSsl");
                _bEnableSsl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bEnableSsl");
                OnbEnableSslChanged();
            }
        }
        private Nullable<global::System.Boolean> _bEnableSsl;
        partial void OnbEnableSslChanging(Nullable<global::System.Boolean> value);
        partial void OnbEnableSslChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sCcMail
        {
            get
            {
                return _sCcMail;
            }
            set
            {
                OnsCcMailChanging(value);
                ReportPropertyChanging("sCcMail");
                _sCcMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sCcMail");
                OnsCcMailChanged();
            }
        }
        private global::System.String _sCcMail;
        partial void OnsCcMailChanging(global::System.String value);
        partial void OnsCcMailChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetPerfiles_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetPerfiles_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetPerfiles_Result.
        /// </summary>
        /// <param name="idPerfil">Valor inicial de la propiedad IdPerfil.</param>
        /// <param name="perfil">Valor inicial de la propiedad Perfil.</param>
        public static spGetPerfiles_Result CreatespGetPerfiles_Result(global::System.Int32 idPerfil, global::System.String perfil)
        {
            spGetPerfiles_Result spGetPerfiles_Result = new spGetPerfiles_Result();
            spGetPerfiles_Result.IdPerfil = idPerfil;
            spGetPerfiles_Result.Perfil = perfil;
            return spGetPerfiles_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPerfil
        {
            get
            {
                return _IdPerfil;
            }
            set
            {
                OnIdPerfilChanging(value);
                ReportPropertyChanging("IdPerfil");
                _IdPerfil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPerfil");
                OnIdPerfilChanged();
            }
        }
        private global::System.Int32 _IdPerfil;
        partial void OnIdPerfilChanging(global::System.Int32 value);
        partial void OnIdPerfilChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Perfil
        {
            get
            {
                return _Perfil;
            }
            set
            {
                OnPerfilChanging(value);
                ReportPropertyChanging("Perfil");
                _Perfil = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Perfil");
                OnPerfilChanged();
            }
        }
        private global::System.String _Perfil;
        partial void OnPerfilChanging(global::System.String value);
        partial void OnPerfilChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetTipoTramite_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetTipoTramite_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetTipoTramite_Result.
        /// </summary>
        /// <param name="idTipoTramite">Valor inicial de la propiedad IdTipoTramite.</param>
        /// <param name="tipoTramite">Valor inicial de la propiedad TipoTramite.</param>
        /// <param name="estado">Valor inicial de la propiedad Estado.</param>
        public static spGetTipoTramite_Result CreatespGetTipoTramite_Result(global::System.Int32 idTipoTramite, global::System.String tipoTramite, global::System.Boolean estado)
        {
            spGetTipoTramite_Result spGetTipoTramite_Result = new spGetTipoTramite_Result();
            spGetTipoTramite_Result.IdTipoTramite = idTipoTramite;
            spGetTipoTramite_Result.TipoTramite = tipoTramite;
            spGetTipoTramite_Result.Estado = estado;
            return spGetTipoTramite_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoTramite
        {
            get
            {
                return _IdTipoTramite;
            }
            set
            {
                OnIdTipoTramiteChanging(value);
                ReportPropertyChanging("IdTipoTramite");
                _IdTipoTramite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoTramite");
                OnIdTipoTramiteChanged();
            }
        }
        private global::System.Int32 _IdTipoTramite;
        partial void OnIdTipoTramiteChanging(global::System.Int32 value);
        partial void OnIdTipoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoTramite
        {
            get
            {
                return _TipoTramite;
            }
            set
            {
                OnTipoTramiteChanging(value);
                ReportPropertyChanging("TipoTramite");
                _TipoTramite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoTramite");
                OnTipoTramiteChanged();
            }
        }
        private global::System.String _TipoTramite;
        partial void OnTipoTramiteChanging(global::System.String value);
        partial void OnTipoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.Boolean _Estado;
        partial void OnEstadoChanging(global::System.Boolean value);
        partial void OnEstadoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetTipoTramiteBySolicitud_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetTipoTramiteBySolicitud_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetTipoTramiteBySolicitud_Result.
        /// </summary>
        /// <param name="tipoTramite">Valor inicial de la propiedad TipoTramite.</param>
        public static spGetTipoTramiteBySolicitud_Result CreatespGetTipoTramiteBySolicitud_Result(global::System.String tipoTramite)
        {
            spGetTipoTramiteBySolicitud_Result spGetTipoTramiteBySolicitud_Result = new spGetTipoTramiteBySolicitud_Result();
            spGetTipoTramiteBySolicitud_Result.TipoTramite = tipoTramite;
            return spGetTipoTramiteBySolicitud_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoTramite
        {
            get
            {
                return _IdTipoTramite;
            }
            set
            {
                OnIdTipoTramiteChanging(value);
                ReportPropertyChanging("IdTipoTramite");
                _IdTipoTramite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoTramite");
                OnIdTipoTramiteChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoTramite;
        partial void OnIdTipoTramiteChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoTramite
        {
            get
            {
                return _TipoTramite;
            }
            set
            {
                OnTipoTramiteChanging(value);
                ReportPropertyChanging("TipoTramite");
                _TipoTramite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoTramite");
                OnTipoTramiteChanged();
            }
        }
        private global::System.String _TipoTramite;
        partial void OnTipoTramiteChanging(global::System.String value);
        partial void OnTipoTramiteChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spGetUsuarioTipoTramite_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spGetUsuarioTipoTramite_Result : ComplexObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto spGetUsuarioTipoTramite_Result.
        /// </summary>
        /// <param name="sUsuario">Valor inicial de la propiedad sUsuario.</param>
        /// <param name="nIdTipoTramite">Valor inicial de la propiedad nIdTipoTramite.</param>
        /// <param name="tipoTramite">Valor inicial de la propiedad TipoTramite.</param>
        /// <param name="dFecha">Valor inicial de la propiedad dFecha.</param>
        /// <param name="nEstado">Valor inicial de la propiedad nEstado.</param>
        public static spGetUsuarioTipoTramite_Result CreatespGetUsuarioTipoTramite_Result(global::System.String sUsuario, global::System.Int32 nIdTipoTramite, global::System.String tipoTramite, global::System.DateTime dFecha, global::System.Int32 nEstado)
        {
            spGetUsuarioTipoTramite_Result spGetUsuarioTipoTramite_Result = new spGetUsuarioTipoTramite_Result();
            spGetUsuarioTipoTramite_Result.sUsuario = sUsuario;
            spGetUsuarioTipoTramite_Result.nIdTipoTramite = nIdTipoTramite;
            spGetUsuarioTipoTramite_Result.TipoTramite = tipoTramite;
            spGetUsuarioTipoTramite_Result.dFecha = dFecha;
            spGetUsuarioTipoTramite_Result.nEstado = nEstado;
            return spGetUsuarioTipoTramite_Result;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sUsuario
        {
            get
            {
                return _sUsuario;
            }
            set
            {
                OnsUsuarioChanging(value);
                ReportPropertyChanging("sUsuario");
                _sUsuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sUsuario");
                OnsUsuarioChanged();
            }
        }
        private global::System.String _sUsuario;
        partial void OnsUsuarioChanging(global::System.String value);
        partial void OnsUsuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nIdTipoTramite
        {
            get
            {
                return _nIdTipoTramite;
            }
            set
            {
                OnnIdTipoTramiteChanging(value);
                ReportPropertyChanging("nIdTipoTramite");
                _nIdTipoTramite = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nIdTipoTramite");
                OnnIdTipoTramiteChanged();
            }
        }
        private global::System.Int32 _nIdTipoTramite;
        partial void OnnIdTipoTramiteChanging(global::System.Int32 value);
        partial void OnnIdTipoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoTramite
        {
            get
            {
                return _TipoTramite;
            }
            set
            {
                OnTipoTramiteChanging(value);
                ReportPropertyChanging("TipoTramite");
                _TipoTramite = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoTramite");
                OnTipoTramiteChanged();
            }
        }
        private global::System.String _TipoTramite;
        partial void OnTipoTramiteChanging(global::System.String value);
        partial void OnTipoTramiteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dFecha
        {
            get
            {
                return _dFecha;
            }
            set
            {
                OndFechaChanging(value);
                ReportPropertyChanging("dFecha");
                _dFecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFecha");
                OndFechaChanged();
            }
        }
        private global::System.DateTime _dFecha;
        partial void OndFechaChanging(global::System.DateTime value);
        partial void OndFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 nEstado
        {
            get
            {
                return _nEstado;
            }
            set
            {
                OnnEstadoChanging(value);
                ReportPropertyChanging("nEstado");
                _nEstado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nEstado");
                OnnEstadoChanged();
            }
        }
        private global::System.Int32 _nEstado;
        partial void OnnEstadoChanging(global::System.Int32 value);
        partial void OnnEstadoChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spInsDelValUsuarioTipoTramite_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spInsDelValUsuarioTipoTramite_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> nResult
        {
            get
            {
                return _nResult;
            }
            set
            {
                OnnResultChanging(value);
                ReportPropertyChanging("nResult");
                _nResult = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("nResult");
                OnnResultChanged();
            }
        }
        private Nullable<global::System.Int32> _nResult;
        partial void OnnResultChanging(Nullable<global::System.Int32> value);
        partial void OnnResultChanged();

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CuraduriaModel", Name="spInsertarImagenes_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spInsertarImagenes_Result : ComplexObject
    {
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String resultado
        {
            get
            {
                return _resultado;
            }
            set
            {
                OnresultadoChanging(value);
                ReportPropertyChanging("resultado");
                _resultado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("resultado");
                OnresultadoChanged();
            }
        }
        private global::System.String _resultado;
        partial void OnresultadoChanging(global::System.String value);
        partial void OnresultadoChanged();

        #endregion

    }

    #endregion

    
}
